campaign: ORCESTRA
campaign_id: ORCESTRA
platform: Sal
platform_number: 1
location: Deebles Point
configs:
    main: config/main_cor.yaml  # name of this file
    level0: config/level0_cor.yml
    level1: config/level1_cor.yaml
    level2: config/level2.yaml
